# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inst < Formula
  desc "Instill AI's command-line tool"
  homepage "https://github.com/instill-ai/cli"
  version "0.3.1-alpha"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/instill-ai/cli/releases/download/v0.3.1-alpha/inst_Darwin_x86_64.tar.gz"
    sha256 "c9a38f579d2b9a0214cd5f19be67b5231eff768efed2e6b5543801c9e21130ab"

    def install
      bin.install "bin/inst"
      (bash_completion/"inst").write `#{bin}/inst completion -s bash`
      (fish_completion/"inst.fish").write `#{bin}/inst completion -s fish`
      (zsh_completion/"_inst").write `#{bin}/inst completion -s zsh`
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Inst
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/instill-ai/cli/releases/download/v0.3.1-alpha/inst_Linux_armv6.tar.gz"
      sha256 "bbd77a47d9594b7befbf284c71de448fb482e259f564f13a58c76a84bc9efe22"

      def install
        bin.install "bin/inst"
        (bash_completion/"inst").write `#{bin}/inst completion -s bash`
        (fish_completion/"inst.fish").write `#{bin}/inst completion -s fish`
        (zsh_completion/"_inst").write `#{bin}/inst completion -s zsh`
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/instill-ai/cli/releases/download/v0.3.1-alpha/inst_Linux_arm64.tar.gz"
      sha256 "75f79ce70785f8410830fcb36292379d0695883bac18485a11d79c59c415ab75"

      def install
        bin.install "bin/inst"
        (bash_completion/"inst").write `#{bin}/inst completion -s bash`
        (fish_completion/"inst.fish").write `#{bin}/inst completion -s fish`
        (zsh_completion/"_inst").write `#{bin}/inst completion -s zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/instill-ai/cli/releases/download/v0.3.1-alpha/inst_Linux_x86_64.tar.gz"
      sha256 "c8c4dcb73d601ca8fdfa8c8dd1eb823d1b3c45d47cf8f2e64323550316ae4989"

      def install
        bin.install "bin/inst"
        (bash_completion/"inst").write `#{bin}/inst completion -s bash`
        (fish_completion/"inst.fish").write `#{bin}/inst completion -s fish`
        (zsh_completion/"_inst").write `#{bin}/inst completion -s zsh`
      end
    end
  end

  test do
    assert_match "inst version #{version}", shell_output("#{bin}/inst --version")
  end
end
