# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Instill < Formula
  desc "Instill AI's official command-line tool"
  homepage "https://github.com/instill-ai/cli"
  version "0.1.0-alpha"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/instill-ai/cli/releases/download/v0.1.0-alpha/instill_0.1.0-alpha_macOS_amd64.tar.gz"
      sha256 "037d71ee8657f19a7730eb6fff44cadf3d0560f5c8a6b60f10c1b7f3369fc92f"

      def install
        bin.install "bin/instill"
        (bash_completion/"instill").write `#{bin}/instill completion -s bash`
        (fish_completion/"instill.fish").write `#{bin}/instill completion -s fish`
        (zsh_completion/"_instill").write `#{bin}/instill completion -s zsh`
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/instill-ai/cli/releases/download/v0.1.0-alpha/instill_0.1.0-alpha_linux_amd64.tar.gz"
      sha256 "413bb5cca1629c7c023e1c2d777d614ae93b7bbd9efdc2b19ed3fb7e217d5b30"

      def install
        bin.install "bin/instill"
        (bash_completion/"instill").write `#{bin}/instill completion -s bash`
        (fish_completion/"instill.fish").write `#{bin}/instill completion -s fish`
        (zsh_completion/"_instill").write `#{bin}/instill completion -s zsh`
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/instill-ai/cli/releases/download/v0.1.0-alpha/instill_0.1.0-alpha_linux_armv6.tar.gz"
      sha256 "b404d9d1040ca8ed984f388a178f75fb8efd14cc997c95b50570c23ddfbd2bf3"

      def install
        bin.install "bin/instill"
        (bash_completion/"instill").write `#{bin}/instill completion -s bash`
        (fish_completion/"instill.fish").write `#{bin}/instill completion -s fish`
        (zsh_completion/"_instill").write `#{bin}/instill completion -s zsh`
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/instill-ai/cli/releases/download/v0.1.0-alpha/instill_0.1.0-alpha_linux_arm64.tar.gz"
      sha256 "90a2265b348616260c6ea8402983c33b635ff25744f4b09e0e572be792c9a3d3"

      def install
        bin.install "bin/instill"
        (bash_completion/"instill").write `#{bin}/instill completion -s bash`
        (fish_completion/"instill.fish").write `#{bin}/instill completion -s fish`
        (zsh_completion/"_instill").write `#{bin}/instill completion -s zsh`
      end
    end
  end

  test do
    assert_match "instill version #{version}", shell_output("#{bin}/instill --version")
  end
end
