# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Inst < Formula
  desc "Instill AI's command-line tool"
  homepage "https://github.com/instill-ai/cli"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    url "https://github.com/instill-ai/cli/releases/download/v0.4.0/inst_Darwin_x86_64.tar.gz"
    sha256 "d492cd3a30e7285c30068ac21c1a4bebd501995d9d9a13439cab27e937467a5f"

    def install
      bin.install "bin/inst"
      (bash_completion/"inst").write `#{bin}/inst completion -s bash`
      (fish_completion/"inst.fish").write `#{bin}/inst completion -s fish`
      (zsh_completion/"_inst").write `#{bin}/inst completion -s zsh`
    end

    if Hardware::CPU.arm?
      def caveats
        <<~EOS
          The darwin_arm64 architecture is not supported for the Inst
          formula at this time. The darwin_amd64 binary may work in compatibility
          mode, but it might not be fully supported.
        EOS
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/instill-ai/cli/releases/download/v0.4.0/inst_Linux_arm64.tar.gz"
      sha256 "96180196340090dc1131d9183039e7d89c6933120b6948894185cf327455a042"

      def install
        bin.install "bin/inst"
        (bash_completion/"inst").write `#{bin}/inst completion -s bash`
        (fish_completion/"inst.fish").write `#{bin}/inst completion -s fish`
        (zsh_completion/"_inst").write `#{bin}/inst completion -s zsh`
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/instill-ai/cli/releases/download/v0.4.0/inst_Linux_x86_64.tar.gz"
      sha256 "c0ca5e76374f61e9364964c01368bceb06a0c99370a1b51f9abd9e4dcaabab86"

      def install
        bin.install "bin/inst"
        (bash_completion/"inst").write `#{bin}/inst completion -s bash`
        (fish_completion/"inst.fish").write `#{bin}/inst completion -s fish`
        (zsh_completion/"_inst").write `#{bin}/inst completion -s zsh`
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/instill-ai/cli/releases/download/v0.4.0/inst_Linux_armv6.tar.gz"
      sha256 "4fcab2cf82bd0edc3dd4313679b4712d599fe419a8afcc5e176ae830a58d5270"

      def install
        bin.install "bin/inst"
        (bash_completion/"inst").write `#{bin}/inst completion -s bash`
        (fish_completion/"inst.fish").write `#{bin}/inst completion -s fish`
        (zsh_completion/"_inst").write `#{bin}/inst completion -s zsh`
      end
    end
  end

  test do
    assert_match "inst version #{version}", shell_output("#{bin}/inst --version")
  end
end
